### ISSUE TITLE
How to run when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [CrynetLogistics/raytrace#5]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/118532882-07d19180-b77a-11eb-91c4-c1b1ec8291cf.png)

thank you  
best regards to you  
William

**Comment by CrynetLogistics** [comment]
Hi William
Thank you for your message. Good to hear from you.
I'm afraid it could be due to a number of reasons actually - this project was built quite some years ago, and nvcc/cuda/the toolchains have evolved significantly since then. The latest GPU I've tested this on is a GTX580 - 7 Generations old!

Regards
Crynet
